from ubuntu:20.04

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y python3-sklearn python3-pandas python3-seaborn python3-matplotlib r-cran-ggplot2 r-cran-dplyr
RUN DEBIAN_FRONTEND=noninteractive apt install -y cargo rustc
